### ISSUE TITLE
MobileTest

### ISSUE THREAD

**Issue by bdmcewen** [Adam1400/cs350#10]
Tested from android device, took pictures from phone and posted everything works smoothly. Good job. the only thing I noticed that I would look into is the load time on the images. It doesn't appear there is any compression happening so images taken from the phone are original size.

**Comment by Adam1400** [comment]
Ben, that's a great point. I always figured the pictures loaded slowly because they were being fetched from amazon. I had not thought about compression being the issue. We choose to not compress the pics because we wanted to maintain the visual fidelity.... but, perhaps a little compression never hurt anyone. Thanks for that suggestion!

**Comment by Adam1400** [comment]
This has been somewhat fixed... you have to jump through a lot of hoops when you host pics on amazon s3. As a temp fix we are limiting the max size of the pictures. Pictures will be rendered at a max of 45rem (although they are not compressed yet).
