### ISSUE TITLE
Sign-up goes straight to forcing users to then sign-in.

### ISSUE THREAD

**Issue by maknop** [Adam1400/cs350#4]
Once a user creates an account, it should go straight to application home page.

**Comment by Adam1400** [comment]
Ill see what I can do. I agree that would make more sense. I don't remember off the top of my head.... but I believe that we redirect the user to login because it does not auto sign them in. Taking them back to the home page would prompt a sign in regardless. However if that's not the case I will implement your suggestion. Thanks!

**Comment by Adam1400** [comment]
Got this working! Thanks again for the feedback.
